env: 
#  ENCRYPTED
    USER_NAME: ""
    USER_EMAIL: ""
    BUILD_USER: ""
    BUILD_HOST: "h"
    TG_TOKEN: ""
    TG_CHAT_ID: ""
    GH_TOKEN: ""
    
#  CIRRUS CONFIG
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
       
task:
  name: "Kernel deploy..."
  timeout_in: 2h
  container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G

  Environment_script:
      - export DEBIAN_FRONTEND=noninteractive
      - cat /etc/os*
      - env
      - git config --global user.name "$USER_NAME"
      - git config --global user.email "$USER_EMAIL"
      - export TZ=Asia/Jakarta

  Sync_script:
      - ./sync.sh

  Compile_Proton_script:
      - ./proton-compile.sh
